Camel SFTP / DB Demo
====================

Pre-requisites
==============

* Download and install H2 - http://www.h2database.com/h2-2014-01-18.zip (version 170)

* Open a Terminal and move to the directory bin of H2 database

* Start the engine using the command

    ./h2.sh


Instructions
============

1) Run project locally

* Edit the file resources/config.properties and define your username, password to connect to the SFTP Server

username=yyyyy
password=xxxxx

Change also the location of your SFTP Send/Receive directory

sft_send_path=
sftp_receive_path=

* Create the Send/rceive directories

  mkdir ~/Temp/sftp/receive
  mkdir ~/Temp/sftp/send

* To run the project, open a unix terminal and launch this command

    mvn camel:run

REMARK : The H2 DB must be started before to launch camel:run

* To verify that response has been received from SFTP server, run the following select `SELECT * FROM REQUEST`
query and validate that the column response should contain a content

https://bytebucket.org/cmoulliard/demo-camel-sftp-db/raw/e7a986c9aff1141b2d4480e2f65cc1d5fa91efd1/result.png?token=b117247599f7b8fdbdff9fc71268f5f6099418cf[Result]

2) Run on JBoss Fuse

* Download and install https://repository.jboss.org/nexus/content/groups/ea/io/fabric8/fabric8-karaf/1.0.0.redhat-372//[JBoss Fuse 6.1]
* Open a terminal and move to the bin directory
* Before to start the server, edit the file ../etc/users.properties and uncomment #admin=admin,admin line
* Start JBoss Fuse
    ./fusefabric
* Setup Fabric server when the Karaf console appears
    fabric:create
* Deploy the profile of the project by running this command after https://github.com/fabric8io/fabric8/blob/master/docs/mavenPlugin.md#configuring-the-plugin[changing your maven settings.xml file]
    mvn fabric8:deploy
* If the build succeeds, connect to the web console to verify that the profile has been created using the hawtio web console - [url](http://localhost:8181/hawtio/index.html#/wiki/branch/1.0/view/fabric/profiles/sftp/db/demo.profile) where you can control
that a profile using `camel, camel-ftp, camel-spring ...` has been created

or run this command on the command line of the root container to display the content of the profile

    fabric:profile-display sftp-db-demo
    Profile id: sftp-db-demo
    Version   : 1.0
    Attributes:
    	parents: feature-camel
    Containers:

    Container settings
    ----------------------------
    Features :
    	camel-core
    	camel-spring
    	spring
    	spring-jdbc
    	fabric-bundle
    	camel-ftp

    Bundles :
    	wrap:mvn:com.h2database/h2/1.3.170
    	mvn:org.jboss.fuse/demo-camel/1.0-SNAPSHOT

* Next create a new Fuse container using this profile

     fabric:container-create-child --profile sftp-db-demo --jmx-user admin --jmx-password admin root demo

* Connect to the server and look to the log to see if messages / files have been received from the SFTP Server

DB Access
=========

* You can check that a record has been created in the H2 DB as we upload one record when the camel project is created/started

* Your browser should be opened with this address : http://192.168.1.3:8082/

    GenericH2 Server
    URL : jdbc:h2:tcp://localhost/~/Temp/TEST
    User : sa
    Password:


* Verify that a record has been created

    SELECT * FROM REQUEST




